ERROR 2025-05-15 17:44:26,374 log Internal Server Error: /admin/users/user/
Traceback (most recent call last):
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\db\models\options.py", line 681, in get_field
    return self.fields_map[field_name]
KeyError: 'avatar_preview'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\contrib\admin\utils.py", line 272, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\contrib\admin\utils.py", line 303, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\db\models\options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: User has no field named 'avatar_preview'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\response.py", line 111, in render
    self.content = self.rendered_content
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\response.py", line 89, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 336, in result_list
    "results": list(results(cl)),
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\contrib\admin\utils.py", line 281, in lookup_field
    value = attr(obj)
  File "C:\Users\howdo\Desktop\CoinsGram\backend\users\admin.py", line 25, in avatar_preview
    return mark_safe(f'<img src="{obj.avatar.url}" width="50"/>')
NameError: name 'mark_safe' is not defined
ERROR 2025-05-15 17:44:26,388 basehttp "GET /admin/users/user/ HTTP/1.1" 500 414239
ERROR 2025-05-15 23:45:10,724 log Internal Server Error: /api/docs/
Traceback (most recent call last):
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\response.py", line 111, in render
    self.content = self.rendered_content
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\rest_framework\renderers.py", line 160, in render
    template = self.resolve_template(template_names)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\rest_framework\renderers.py", line 170, in resolve_template
    return loader.select_template(template_names)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: redoc/custom_redoc.html
ERROR 2025-05-15 23:45:10,732 basehttp "GET /api/docs/ HTTP/1.1" 500 100396
ERROR 2025-05-15 23:49:02,214 log Internal Server Error: /api/docs/
Traceback (most recent call last):
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\response.py", line 111, in render
    self.content = self.rendered_content
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\rest_framework\renderers.py", line 160, in render
    template = self.resolve_template(template_names)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\rest_framework\renderers.py", line 170, in resolve_template
    return loader.select_template(template_names)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: redoc.html
ERROR 2025-05-15 23:49:02,225 basehttp "GET /api/docs/ HTTP/1.1" 500 100123
ERROR 2025-05-16 15:00:24,173 log Internal Server Error: /api/favorites/download/
Traceback (most recent call last):
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\howdo\Desktop\CoinsGram\backend\api\views.py", line 189, in download
    response = HttpResponse(
NameError: name 'HttpResponse' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\rest_framework\views.py", line 472, in handle_exception
    response = exception_handler(exc, context)
  File "C:\Users\howdo\Desktop\CoinsGram\backend\api\middleware.py", line 22, in custom_exception_handler
    if isinstance(exc, django.core.exceptions.ValidationError):
NameError: name 'django' is not defined
ERROR 2025-05-16 15:00:24,177 basehttp "GET /api/favorites/download/ HTTP/1.1" 500 104511
ERROR 2025-05-16 15:02:37,329 log Internal Server Error: /api/favorites/download/
Traceback (most recent call last):
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\howdo\Desktop\CoinsGram\backend\api\views.py", line 189, in download
    response = HttpResponse(
NameError: name 'HttpResponse' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\howdo\Desktop\CoinsGram\venv\lib\site-packages\rest_framework\views.py", line 472, in handle_exception
    response = exception_handler(exc, context)
  File "C:\Users\howdo\Desktop\CoinsGram\backend\api\middleware.py", line 22, in custom_exception_handler
    if isinstance(exc, django.core.exceptions.ValidationError):
NameError: name 'django' is not defined
ERROR 2025-05-16 15:02:37,329 basehttp "GET /api/favorites/download/ HTTP/1.1" 500 104511
